### ISSUE TITLE
Add support for other ores

### ISSUE THREAD

**Issue by tyra314** [Mowmaster/Realistic-Processing#1]
I really like your mod, what I'm missing is support for other modded ores, like tin, copper, etc.
It would also be great to use oreDict, so for instance iron gravel ores will also work.

I think a suitable solution would be to add a config file, which allows you to config `input ore -> output item` and the used fuel.

*edit: Ideally you could also configure the amount of results you get. Also MineTweaker support may help with that.

**Comment by Mowmaster** [comment]
@I have plans to do this, This is the first mod I have ever mad a machine for so its all hard coded at this time.

[Project To-Do's](https://trello.com/b/5x3AV7i2/mod-realistic-processing)

Ores - All hard coded and I would have to research and ask around for how to make this allow other types easily.
Config - Shouldn't be too hard as the values I use for things like ore output and cook time, etc are all easy to make into a config. (Moved higher on my to-do list)
API - MT support etc. Now idea how this works, would probably have to figure out Ores first. Also would like to hold off till I push a release as I plan to expand on my ideas for this mod. Bloomery produces metal blooms that must be forged into ingots, etc... 

~~~~Time Frame~~~~
I can probably get the config out in the next update, the Ores will come later as I need to figure it out for my main project anyway, ill probably push that out once I figure that out there. I dont see api/mt support anytime soon so any additions there would have to be requested till i do figure it out.

**Comment by Mowmaster** [comment]
Currently rewriting this tile entity to accept any ore with an OreDictionary name containing "ore" and if it has a smelting output, I admit this isn't the best solution but one I will work with until a recipe. Manager is implemented. 
https://github.com/Mowmaster/Realistic-Processing/commit/8ddb9598767f868cc9481dd1824b9efbd86b2132
Support for this feature exists in this commit but the block is not yet fully functional, will commit again later finishing this.
